mysql:
  db_host: "{{ groups['dbserver'][0] }}"
  socket: /var/run/mysqld/mysqld.sock
  db: wpdb
  user: wpadm
  passwd: P@ssw0rd
  bind_path: /etc/mysql/mysql.conf.d/mysqld.cnf
  bind_address: 0.0.0.0
